### PR TITLE
Xcode9.3

### PR DESCRIPTION
**Pull request by alessandro-martin**
- Settings updated for Xcode 9.3
- Swift 4 conversion (no code changes)
- Minor cleanup

### CODE REVIEW

**Comment by thomassnielsen** [comment]
Thank you for helping keeping this library up to date! I see that this branch fails on Travis. Unfortunately I don't have Xcode 9.3 (I'm still not on High Sierra), so I cannot investigate much myself. I see that the travis config still points to Xcode 8, so that might be the issue. @alessandro-martin would you mind updating `.travis.yml` in this branch with Xcode 9? It seems like [Travis is not quite ready with 9.3](https://docs.travis-ci.com/user/reference/osx/) yet, so you might want to try `9.2` or `9.3beta` until 9.3 is in place.

**Comment by alessandro-martin** [comment]
Sure thing @thomassnielsen, I'll update the `.travis.yml` and let's see if it fixes the issue.

**Comment by alessandro-martin** [comment]
@thomassnielsen not working but I think it may have something to do with 
`-destination 'platform=iOS Simulator,id=86B2CA7C-0247-4257-BFEA-8035084AF2CF'`
which may not be available in Xcode 9.2 beta.
I'll try using a more "generic" simulator

**Comment by thomassnielsen** [comment]
There's a list of available simulators in the error log:
https://api.travis-ci.org/v3/job/360917405/log.txt

**Comment by alessandro-martin** [comment]
@thomassnielsen all checks have passed :)
I chose to go for
`-destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3'`
to avoid being tied to a (too) specific simulator version; I hope you're cool with this approach.

**Comment by thomassnielsen** [comment]
Awesome, great work on updating to the latest syntax as well 👍

**Pull request merged**
