### PR TITLE
Errors and Meta

### PR DESCRIPTION
**Pull request by billyto**
Any feedback is welcome!

### CODE REVIEW

**Comment by thomassnielsen** [comment]
The code looks good. I suggest that you make a new test jsonapi document with the errors, so we don't have errors in our only test document. If we in the future introduce `hasErrors` or something similar, we will need at least one document with and one without an error.

Before I merge I want to fix a few things:
- The CircleCI setup isn't picking up the tests (#2)
- I see that there are a few xcode project files in this PR. I'll update the .gitignore to cover these

You may have to rebase this PR after I do those updates.

**Comment by thomassnielsen** [comment]
I've added a `.gitignore` (totally my bad that it was missing in the first place). If you could rebase and make sure that your xcuserdata isn't committed that would be great.

After rebase and committing any changes, this should remove any checked in files covered by the new `.gitignore`:

```
git rm -r --cached .
git add .
```

**Comment by billyto** [comment]
Good catch! got rid of xcuserdata and moved errors to their own file.

**Comment by thomassnielsen** [comment]
I've configured Travis CI now, can you try bumping this PR to triggering a test run?

**Comment by thomassnielsen** [comment]
After merging #3, this needs a rebase.

**Comment by billyto** [comment]
Rebased!

**Pull request merged**
