### PR TITLE
Support Swift 5.0

### PR DESCRIPTION
**Pull request by damienvieira**
- Swift 5 conversion with no code changes
- Settings updated for Xcode 10.2

### CODE REVIEW

**Review by jfsagasti — APPROVED** [review]

**Review by alessandro-martin — APPROVED** [review]
LGTM!

**Comment by damienvieira** [comment]
Hi @thomassnielsen, do you know when you will be able to merge this PR and create a new tag?

**Comment by thomassnielsen** [comment]
Hi! I can look at it now, got a few minutes before the keynote 😁

**Comment by thomassnielsen** [comment]
0.1.0 deployed to CocoaPods

**Comment by damienvieira** [comment]
Awesome thanks @thomassnielsen! 🥇

**Pull request merged**
